name: carbon_stores
description: "CarbonGurukulam Store - POS System"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: any
  cloud_firestore: any

  # State Management
  flutter_riverpod: ^2.6.1

  # UI & Design
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8

  # Charts
  fl_chart: ^0.70.2

  # CSV & File
  csv: ^6.0.0
  share_plus: ^10.1.4
  path_provider: ^2.1.5

  # HTTP
  http: ^1.3.0

  # Utilities
  intl: ^0.19.0
  uuid: ^4.5.1
  connectivity_plus: ^6.1.3
  web: ^1.1.1
  shared_preferences: ^2.3.4
  pdf: ^3.12.0
  printing: ^5.14.3
  image_picker: ^1.2.1
  file_picker: ^11.0.2
  archive: ^4.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  image_path: "assets/images/logo.png"

flutter_native_splash:
  color: "#945B2C"
  android: true
  ios: true
  web: true
  android_12:
    color: "#945B2C"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
