// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0Je8aN088Qj5asiEnlhGZH9NKAK0vaJo',
    appId: '1:618585657398:web:f23f1c521fa0a3c7bc4897',
    messagingSenderId: '618585657398',
    projectId: 'carbon-stores',
    authDomain: 'carbon-stores.firebaseapp.com',
    storageBucket: 'carbon-stores.firebasestorage.app',
    measurementId: 'G-M7X13B4RKP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc4DVuAbeoswh2fsgmHrXLbKtcv9bws3s',
    appId: '1:618585657398:android:2a0479c9b6274583bc4897',
    messagingSenderId: '618585657398',
    projectId: 'carbon-stores',
    storageBucket: 'carbon-stores.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe_vnZG9JvLRjqX6RRPb8bxDUAGsw-0As',
    appId: '1:618585657398:ios:ec2852ab7579817fbc4897',
    messagingSenderId: '618585657398',
    projectId: 'carbon-stores',
    storageBucket: 'carbon-stores.firebasestorage.app',
    iosBundleId: 'com.example.carbonStores',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe_vnZG9JvLRjqX6RRPb8bxDUAGsw-0As',
    appId: '1:618585657398:ios:ec2852ab7579817fbc4897',
    messagingSenderId: '618585657398',
    projectId: 'carbon-stores',
    storageBucket: 'carbon-stores.firebasestorage.app',
    iosBundleId: 'com.example.carbonStores',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0Je8aN088Qj5asiEnlhGZH9NKAK0vaJo',
    appId: '1:618585657398:web:682090571ab957a1bc4897',
    messagingSenderId: '618585657398',
    projectId: 'carbon-stores',
    authDomain: 'carbon-stores.firebaseapp.com',
    storageBucket: 'carbon-stores.firebasestorage.app',
    measurementId: 'G-8R2RRP5KPS',
  );
}
